"""SWaT dataset loader with dummy .npy fallback."""

import os
from typing import List

import numpy as np

from vector.data.registry import BaseLoader, SequenceData, register


@register("SWaT")
class SWaTLoader(BaseLoader):
    """Loader for SWaT (Secure Water Treatment) dataset.

    Supports two formats:
    1. Dummy .npy files generated by scripts/generate_dummy_swat.py
    2. Real iTrust Excel files (SWaT_Dataset_Normal_v1.xlsx, SWaT_Dataset_Attack_v0.xlsx)

    SWaT has 51 sensor dimensions. Requires iTrust registration for real data.
    """

    N_DIMS = 51

    def load(self, data_dir: str) -> List[SequenceData]:
        """Load SWaT data from npy files or iTrust Excel files.

        Args:
            data_dir: Directory containing SWaT data files.

        Returns:
            List with a single SequenceData containing the full dataset.

        Raises:
            FileNotFoundError: If neither dummy nor real data files are found.
        """
        # Try dummy .npy files first
        train_path = os.path.join(data_dir, "train.npy")
        test_path = os.path.join(data_dir, "test.npy")
        labels_path = os.path.join(data_dir, "labels.npy")

        if all(os.path.exists(p) for p in [train_path, test_path, labels_path]):
            train = np.load(train_path)
            test = np.load(test_path)
            labels = np.load(labels_path)
            return [SequenceData(name="SWaT", train=train, test=test, labels=labels)]

        # Try real iTrust Excel format
        normal_path = os.path.join(data_dir, "SWaT_Dataset_Normal_v1.xlsx")
        attack_path = os.path.join(data_dir, "SWaT_Dataset_Attack_v0.xlsx")

        if os.path.exists(normal_path) and os.path.exists(attack_path):
            return self._load_excel(normal_path, attack_path)

        raise FileNotFoundError(
            f"SWaT dataset not found at {data_dir}. "
            "Run scripts/generate_dummy_swat.py for dummy data "
            "or register at iTrust for real data."
        )

    def _load_excel(
        self, normal_path: str, attack_path: str
    ) -> List[SequenceData]:
        """Load real SWaT data from iTrust Excel files."""
        import pandas as pd

        # Normal (train) data -- skip first row (header row after column names)
        train_df = pd.read_excel(normal_path, skiprows=1)
        # Drop timestamp column, keep 51 sensor columns
        train_df = train_df.drop(columns=[train_df.columns[0]])
        # Drop the label column if present
        if "Normal/Attack" in train_df.columns:
            train_df = train_df.drop(columns=["Normal/Attack"])
        train = train_df.values[:, : self.N_DIMS].astype(np.float64)

        # Attack (test) data
        test_df = pd.read_excel(attack_path, skiprows=1)
        test_df_clean = test_df.drop(columns=[test_df.columns[0]])
        # Extract labels from Normal/Attack column
        label_col = test_df_clean["Normal/Attack"]
        labels = (label_col.str.strip() == "Attack").astype(np.int32).values
        test_df_clean = test_df_clean.drop(columns=["Normal/Attack"])
        test = test_df_clean.values[:, : self.N_DIMS].astype(np.float64)

        return [SequenceData(name="SWaT", train=train, test=test, labels=labels)]
