"""WADI dataset loader with dummy .npy fallback."""

import os
from typing import List

import numpy as np

from vector.data.registry import BaseLoader, SequenceData, register


# Metadata columns to drop from raw WADI CSVs
_DROP_COLUMNS = [
    "2_LS_001_AL",
    "2_LS_002_AL",
    "2_P_001_STATUS",
    "2_P_002_STATUS",
]


@register("WADI")
class WADILoader(BaseLoader):
    """Loader for WADI (Water Distribution) dataset.

    Supports two formats:
    1. Dummy .npy files generated by scripts/generate_dummy_wadi.py
    2. Real iTrust CSV files

    WADI has 123 sensor dimensions after dropping metadata columns.
    NaN values are filled with 0. Requires iTrust registration for real data.
    """

    N_DIMS = 123

    def load(self, data_dir: str) -> List[SequenceData]:
        """Load WADI data from npy files or iTrust CSV files.

        Args:
            data_dir: Directory containing WADI data files.

        Returns:
            List with a single SequenceData containing the full dataset.

        Raises:
            FileNotFoundError: If neither dummy nor real data files are found.
        """
        # Try dummy .npy files first
        train_path = os.path.join(data_dir, "train.npy")
        test_path = os.path.join(data_dir, "test.npy")
        labels_path = os.path.join(data_dir, "labels.npy")

        if all(os.path.exists(p) for p in [train_path, test_path, labels_path]):
            train = np.load(train_path)
            test = np.load(test_path)
            labels = np.load(labels_path)
            return [SequenceData(name="WADI", train=train, test=test, labels=labels)]

        # Try real iTrust CSV format
        csv_files = [f for f in os.listdir(data_dir) if f.endswith(".csv")] if os.path.isdir(data_dir) else []
        if csv_files:
            return self._load_csv(data_dir, csv_files)

        raise FileNotFoundError(
            f"WADI dataset not found at {data_dir}. "
            "Run scripts/generate_dummy_wadi.py for dummy data "
            "or register at iTrust for real data."
        )

    def _load_csv(
        self, data_dir: str, csv_files: list
    ) -> List[SequenceData]:
        """Load real WADI data from iTrust CSV files."""
        import pandas as pd

        # Find train/test CSVs by name pattern
        train_file = next((f for f in csv_files if "normal" in f.lower() or "train" in f.lower()), csv_files[0])
        test_file = next((f for f in csv_files if "attack" in f.lower() or "test" in f.lower()), csv_files[-1])

        train_df = pd.read_csv(os.path.join(data_dir, train_file))
        test_df = pd.read_csv(os.path.join(data_dir, test_file))

        # Skip first 3 columns (Row, Date, Time)
        train_df = train_df.iloc[:, 3:]
        test_df = test_df.iloc[:, 3:]

        # Drop metadata columns
        for col in _DROP_COLUMNS:
            if col in train_df.columns:
                train_df = train_df.drop(columns=[col])
            if col in test_df.columns:
                test_df = test_df.drop(columns=[col])

        # Extract labels if present (last column typically)
        if "Attack" in test_df.columns or "Label" in test_df.columns:
            label_col = "Attack" if "Attack" in test_df.columns else "Label"
            labels = test_df[label_col].values.astype(np.int32)
            test_df = test_df.drop(columns=[label_col])
        else:
            # Default: no labels available
            labels = np.zeros(len(test_df), dtype=np.int32)

        # Convert to float, fill NaN with 0
        train = np.nan_to_num(train_df.values.astype(np.float64), nan=0.0)
        test = np.nan_to_num(test_df.values.astype(np.float64), nan=0.0)

        return [SequenceData(name="WADI", train=train, test=test, labels=labels)]
